package gui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import model.Fallapop;
import model.Producto;

public class Favoritos extends javax.swing.JPanel {

    private Fallapop fallapop;
    private VentanaPrincipal ventana;

    public Favoritos(VentanaPrincipal ventana, Fallapop fallapop) {
        initComponents();

        this.fallapop = fallapop;
        this.ventana = ventana;

        iniciarInterfaz();
    }

    public void iniciarInterfaz(){
        botonContactar.addActionListener(e -> {
            Producto seleccionado = favoritosList.getSelectedValue();

            if(seleccionado == null){
                JOptionPane.showMessageDialog(
                        ventana, 
                        "No ha seleccionado ningún producto.", 
                        "Erro: Ningún producto seleccionado", 
                        JOptionPane.ERROR_MESSAGE
                );

                return;
            }
            
            //TODO: Create contact window
        });

        botonEliminar.addActionListener(e -> {
            Producto seleccionado = favoritosList.getSelectedValue();

            fallapop.getUsuarioLogeado().eliminarFavorito(seleccionado);
            configurar();
        });

        favoritosList.addListSelectionListener(e -> {
            Producto seleccionado = favoritosList.getSelectedValue();

            if(seleccionado != null)
                etiquetaDescripcion.setText(seleccionado.getDescripcion());
        });
    }

    public void configurar(){
        DefaultListModel<Producto> defaultListModel = new DefaultListModel<>();
        defaultListModel.addAll(fallapop.getUsuarioLogeado().getFavoritos());

        favoritosList.setModel(defaultListModel);
        etiquetaDescripcion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        favoritosList = new javax.swing.JList<>();
        botonEliminar = new javax.swing.JButton();
        botonContactar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        etiquetaDescripcion = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jScrollPane1.setViewportView(favoritosList);

        botonEliminar.setText("Eliminar de favoritos");

        botonContactar.setText("Contactar con el vendedor");

        jLabel1.setText("Descripción del producto:");

        etiquetaDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        etiquetaDescripcion.setAlignmentY(0.0F);
        etiquetaDescripcion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonContactar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(etiquetaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonContactar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonContactar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JList<Producto> favoritosList;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
