package gui;

import java.awt.Menu;

public class Navegador extends javax.swing.JPanel {

    private MenuPrincipal menuPrincipal;

    public Navegador(MenuPrincipal menuPrincipal) {
        initComponents();

        this.menuPrincipal = menuPrincipal;

        iniciarInterfaz();
    }

    private void iniciarInterfaz(){
        botonProducto.addActionListener(e -> {
            menuPrincipal.irPanelCatalogo();
        });

        botonFavoritos.addActionListener(e -> {
            menuPrincipal.irListaFavoritos();
        });

        botonHistorial.addActionListener(e -> {
            menuPrincipal.irHistorial();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonProducto = new javax.swing.JButton();
        botonHistorial = new javax.swing.JButton();
        botonFavoritos = new javax.swing.JButton();

        botonProducto.setText("Ver productos");

        botonHistorial.setText("Ver historial de compras");

        botonFavoritos.setText("Ver favoritos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonProducto)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonFavoritos)
                                .addGap(4, 4, 4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonHistorial, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(botonProducto)
                .addGap(18, 18, 18)
                .addComponent(botonHistorial)
                .addGap(18, 18, 18)
                .addComponent(botonFavoritos)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFavoritos;
    private javax.swing.JButton botonHistorial;
    private javax.swing.JButton botonProducto;
    // End of variables declaration//GEN-END:variables
}
